Patches/CardTriggerHandler.cs

This PR fixes a defect in the patch for CardTriggerHandler.AddAbility.
Right now, duplicate stackable NewAbilities are not being added to the trigger list because the predicate is always true for stackable abilities. A stackable ability can only be added if the trigger list is empty.
This changes the if statement so that stackable abilities are properly added to the card.

Fixed CardTriggerHandler to properly add stackable custom abilities

---

InscryptionAPI/Ascension/AscensionChallengePaginator.cs
InscryptionAPI/Ascension/AscensionChallengeScreen.cs
InscryptionAPI/Ascension/AscensionRunSetupScreenBase.cs
InscryptionAPI/Ascension/ChallengeManager.cs
InscryptionAPI/Ascension/StarterDeckManager.cs
InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Card/CardManager.cs
InscryptionAPI/Card/ExtendedAbilityBehaviour.cs
InscryptionAPI/Compatibility/CustomRegion.cs
InscryptionAPI/Compatibility/NewEncounter.cs
InscryptionAPI/Compatibility/NewRegion.cs
InscryptionAPI/Encounters/EncounterManager.cs
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionAPI/Regions/RegionExtensions.cs
InscryptionAPI/Regions/RegionManager.cs
InscryptionCommunityPatch/InscryptionCommunityPatch.csproj
README.md

This PR does two things:
1) Adds backwards-compatibility for regions and encounters
2) Fixes defects in the RegionManager and EncounterManager where the connection between regions, encounters, and the global RegionProgression instance could get desynced due the cloning of objects in the managers.

Encounter compatibility

---

InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Card/CardManager.cs
InscryptionAPI/Compatibility/NewCard.cs
InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
README.md

This PR does two things:
A small thing: it fixes defects in the energy drone manager.
A big thing: It makes the card prefix a required property to CardManager.Add() and .New(); however, it is still optional for mods using the backwards compatibility mode of the API (to prevent old mods from immediately breaking).

Card prefix fixes

---

InscryptionCommunityPatch/Card/Part1CardCostRender.cs
InscryptionCommunityPatch/Card/Part2CardCostRender.cs

This is a very simple bug fix that was reported by teamdoodz in Discord.
The cost render patch was using the private fields instead of the public properties for cost, which meant that they weren't accounting for changes due to the card having CardModificationInfos set on it. This PR switches from the fields to the properties.

Update cost renders to count card mod cost changes

---

InscryptionCommunityPatch/Card/Part1CardCostRender.cs
InscryptionCommunityPatch/Card/Part2CardCostRender.cs

As discovered by VoidSlime: custom card cost render was being incorrectly overwritten by poor cache key construction.
I have removed the card cost cache entirely. This was a very minor technical performance improvement in the first place, as the game already has techniques to prevent cards from being re-rendered every frame. Caching the card cost does prevent it from having to be reassembled, but that reassembly doesn't happen very often.
So I've opted to remove the card cost cache entirely. We can keep an eye on performance and see if this creates any issues in the long run but I don't expect it will.

Card cost cache fix

---

InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Card/CardManager.cs
InscryptionAPI/Card/SpecialStatIconManager.cs
InscryptionAPI/Encounters/BossManager.cs
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionCommunityPatch/Card/ArtPatches.cs

This PR does things:
1) It audits the entire card pool on Start(). Specifically, it looks at three common areas where cards get screwed up: abilities, special abilities, and appearance behaviors attached to cards that haven't been properly registered. Or - more likely - a situation where the user created a card but typo'd the GUID/ability ID. Any issues are put into the log file as warnings.
2) It simplifies the process of creating a Special Stat Icon. When you register a Special Stat Icon, it also registers the appropriate Special Triggered Ability at the same time. And when you use the SetStatIcon extension method to set the stat icon for a card, it automatically attaches the ability.

Card audit and staticons

---

InscryptionCommunityPatch/Card/Part2CardCostRender.cs
InscryptionCommunityPatch/InscryptionCommunityPatchPlugin.cs

Added a config for people who want to opt out of the custom cost and hybrid cost render fix of GBA cards. Not the full version that I wanted to do, but good enough for now while people wait.

stopgap measure for act 2 costs for now

---

InscryptionAPI/Helpers/TextureHelper.cs

This pull request aims to fix #62 by checking if `pathCardArt` is rooted or not, If it is rooted, It's abosolute, If it isn't, It's relative.

feat: Added abosolute path support to `ReadArtworkFileAsBytes`

---

InscryptionAPI/Boons/BoonBehaviour.cs
InscryptionAPI/Boons/BoonManager.cs
InscryptionAPI/Boons/DeckInfoExtensions.cs
InscryptionAPI/Card/TribeManager.cs

@SpecialAPI seems to forget to add a overload for both manager where user can specify path to the image instead of having to supply Texture instead,
Other manager also have the same overload, CardManager, AbilityManager.
I need review from @divisionbyz0rro and @SpecialAPI.

feat: Added "pathTo" overload to Boon and Tribe [...more]

---

InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Helpers/TextureHelper.cs

This PR adds back an extension method that was mistakenly lost in the latest changes to the card extension methods.
This also fixes [this issue](https://github.com/InscryptionModding/InscryptionAPI/issues/67).
And adds XML documentation to TextureHelper

Emissive portrait extensions

---

InscryptionAPI/Guid/GuidManager.cs
InscryptionAPI/Saves/ModdedSaveData.cs
InscryptionAPI/Saves/ModdedSaveManager.cs
docs/namespace/InscryptionAPI.Saves.md

change: Changed the save file folder to be the same as the base one.
docs: Added documentation to `InscryptionAPI.Save` namespace, as well as the save file's methods.
- Why put the modded save file in the same folder as the base one?
- When someone need delete their corrupted save file, they don't have to navigate to two folders, and due to the nature of r2mm, It can sometimes be in different drive too.
- Why add object support to the save file?
- Organization, Less function call, For Example
```cs
var GUID = "this.is.an.example"
ModdedSaveManager.SaveData.GetValue(GUID, "player_progress_map");
ModdedSaveManager.SaveData.GetValue(GUID, "player_progress_tries");
ModdedSaveManager.SaveData.GetValue(GUID, "player_progress_brah");
ModdedSaveManager.SaveData.GetValue(GUID, …
```

feat: Added `object` support to the save file. [...more]

---

InscryptionAPI/Card/AbilityExtensions.cs
InscryptionAPI/Card/AbilityManager.cs

This PR fixes the issues in SetIcon and SetCustomFlippedIcon that were causing users of those methods to set the icon on the wrong copy of the ability.
See issue:
https://github.com/InscryptionModding/InscryptionAPI/issues/95
I also added docs to AbilityManager and AbilityExtensions

Fixed the flipped icon bug

---

InscryptionAPI/Boons/BoonManager.cs
InscryptionAPI/Card/ExtendedAbilityBehaviour.cs
InscryptionAPI/Triggers/Interfaces.cs

This PR adds ExtendedAbilityBehaviour back into the API, but...differently.
It adds three new 'trigger' interfaces (IPassiveAttackBuff, IPassiveHealthBuff, and IGetOpposingSlots), and changes ExtendedAbilityBehaviour to implement those three interfaces.
People who were previously implementing this abstract class still can. People who just want to implement the appropriate interface should do that instead.

Re-added ExtendedAbilityBehaviour

---

InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Card/ExtendedAbilityBehaviour.cs

- This also fixes the `HasSpecialAbility` extension method for PlayableCards to also check TemporaryMods

bugfix: Cards getting buffs after the game ends

---

InscryptionAPI/Card/ExtendedAbilityBehaviour.cs
InscryptionAPI/Helpers/Extensions/BoardManagerExtensions.cs
InscryptionAPI/Helpers/Extensions/CardSlotExtensions.cs
InscryptionCommunityPatch/Card/PassiveAttackBuffPatches.cs

- I kept running into more exceptions that would occur rather randomly during fights that I believe is due to the passive attack buff patch. The new conditional checks should now no longer allow any outlying problems to occur regarding the patch.
- I also added `GetAdjacentCards` extension method to compress some more lines for `BetterAttackBuffs` method along with some minor refactors. with LINQ expressions.

Extra checks for attack buffs + minor extension refactors

---

InscryptionCommunityPatch/Card/ActivatedAbilityHandler3D.cs
InscryptionCommunityPatch/Card/ActivatedAbilityIconFix.cs
InscryptionCommunityPatch/Card/ActivatedAbilityIconInteractable.cs

The current logic for the ability icons assumes that the only way that the card's ability icons can change during a game is by adding new abilities. However, it's possible to change a card and both remove and add abilities at the same time. This PR updates the ability icon interactable fix to always update the card's ability icons when stats change for any reason, and to reset the ability attached to the icon each time.
I tested this using the P03 mod - before this update, activated icons did not work with transform/evolve. They are doing so now.

Improved activated ability icon fix

---

InscryptionAPI/Ascension/AscensionChallengePaginator.cs
InscryptionAPI/Ascension/ChallengeManager.cs
InscryptionCommunityPatch/Card/Part3StatIcons.cs
InscryptionCommunityPatch/Card/PassiveAttackBuffPatches.cs

After approving the previous challenge update, we started plugging in additional mods for testing and found some more incompatibility and inconsistency issues. This makes the following changes:
1) There is no longer a default value for the activated sprite. Based on a cursory survey of the modding landscape, this only appears to affect Curses (my mod). Removing this will make the API behavior more easily predictable.
2) All Add methods now return the same type.
There was also a bug fix for the challenge screen regarding arrow calculations.

Challenge bugfix and Gemified Opponent Cards

---

InscryptionCommunityPatch/Card/AllStrikeAbilityFix.cs

Fixes non-giant cards with Omni Strike always attacking slot 0 if there are no targetable opposing cards
Non-giant cards will now correctly attack their opposing slot

Omni strike fix

---

InscryptionCommunityPatch/Card/Act2LogSpamFixes.cs
InscryptionCommunityPatch/Card/PassiveAttackBuffPatches.cs
InscryptionCommunityPatch/Card/SelfAttackDamagePatch.cs
InscryptionCommunityPatch/Card/SlotAttackSlotFixes.cs
InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs

Fixes multiple instances of console spam in Act 2 due to null instances
Does this by either disabling the offending code if possible (most of the null instance warnings are for instances that aren't used in Act 2 and thus don't need to be called/checked) or making modifications to avoid calling the null instance while in Act 2
Also removes the debug messages from the Act1EnergyDronePatch that inform the user when it's checking the active scene, as they logged at unnecessary times (eg, starting screen, loading screens, etc.)
Miscellaneous tweaks to a couple of my prior fixes that were using TargetMethods instead of TargetMethod

Fixes for console spam in Act 2

---

InscryptionCommunityPatch/Card/Act1LatchAbilityFix.cs

Fixes the Latch fix removing campfire stat boosts when applying a sigil.
Also fixed a render issue with Latched sigils in Grimora's Act.

Fix for Latch deleting campfire boosts

---

InscryptionAPI/Card/AbilityExtensions.cs
InscryptionAPI/Card/AbilityManager.cs
InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Card/CardManager.cs

- Added ExtendedProperties for abilities
- Added new ability setter SetTriggersOncePerStack for controlling the behaviour of stackable abilities after a card evolves
- Added new helper methods for creating cards: SetOnePerDeck, SetHideStats
- Added new helper methods for abilities: SetCanStack, SetTriggersOncePerStack, SetActivated, SetPassive, SetConduit, SetConduitCell
- Added new remover methods for cards: RemoveAbilities, RemoveAbilitiesSingle, RemoveTraits, RemoveTribes
- Grammar fixes for existing helper method descriptions

New helper methods, feature

---

InscryptionAPI/Regions/RegionManager.cs

Rearranges the order of the vanilla game regions in RegionManager.BaseGameRegions, hopefully doesn't screw up anything.

Fixed regions appearing out-of-order in Act 1

---

InscryptionCommunityPatch/Card/Act2LogSpamFixes.cs
InscryptionCommunityPatch/Card/AdditionalIcons.cs
InscryptionCommunityPatch/Card/BoxColliderNegativeScalingLogSpamFix.cs

Allows cards in Acts 2 and 3 to have up to 8 sigils visually displayed. Also adjusted sigil positions in Act 1 slightly.

8-sigil support for Acts 2 and 3

---

InscryptionAPI/Ascension/StarterDeckSelectScreen.cs

Fixed pixel card icons not being properly centred for starter decks with 4+ cards

Starter deck pixel card icons fix

---

CHANGELOG.md
InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Card/CostProperties.cs
InscryptionAPI/Card/OpponentGemsManager.cs
InscryptionAPI/Helpers/ResourcesManagerHelpers.cs
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionAPI/PixelCard/PixelCardManager.cs
InscryptionCommunityPatch/Card/Part1CardCostRender.cs
InscryptionCommunityPatch/Card/Part2CardCostRender.cs
InscryptionCommunityPatch/Card/StackAbilityIcons.cs
InscryptionCommunityPatch/Card/Vanilla Ability Patches/EvolveDescriptionFixes.cs
InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs

- Fixed dynamic costs still not working in Act 2
- Fixed dynamic gem costs checking ResourcesManager instead of OpponentGemsManager for opponent cards
- Fixed dynamic costs not checking for owned blue gems
- Fixed dynamic costs not updating energy display correctly
- Changed dynamic costs to patch SetInfo instead of Awake
- Re-added dynamic cost error messages for when the card or card info is null
- Added ResourcesManager.Instance.GemsOfType(GemType) to check for owned gems of the specified type

Dynamic Cost fixes, new ResourcesManager extension method

---

InscryptionCommunityPatch/ResourceManagers/ActThreeBonesDisplayer.cs

This fixes a bug in the Part 3 Bones Manager.
The ``PoolHasBones`` helper method erroneously checked `EnergyCost` instead of `BonesCost` when checking to see if the active card pool had any cards with a bones cost. This was causing the bones display TV to always appear, even when the player has no bones cards active in Part 3.

Small Part 3 Bones Manager Fix

---

CHANGELOG.md
InscryptionAPI/Ascension/StarterDeckManager.cs
InscryptionAPI/Card/AbilityExtensions.cs
InscryptionAPI/Card/AbilityManager.cs
InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Card/CardManager.cs
InscryptionAPI/Card/DamageShieldBehaviour.cs
InscryptionAPI/Card/ShieldManager.cs
InscryptionAPI/Guid/CustomTypePatches.cs
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionAPI/ResourceBank/ResourceBankManager.cs
InscryptionAPI/Triggers/CustomTriggerPatches.cs
InscryptionAPI/Triggers/Interfaces.cs
InscryptionAPI/Triggers/TakeDamagePatches.cs
InscryptionCommunityPatch/Card/StackAbilityIcons.cs
InscryptionCommunityPatch/Card/Vanilla Ability Patches/SteelTrapFix.cs
docs/wiki/index.md

- Fixed card extension GetAbilityStacks being able to return a negative value for stackable abilities
- Added ability interfaces IModifyDamageTaken, IPreTakeDamage
- Added support for adding alternate portraits specific to the Steel Trap ability effect and broken shield effect
- Added CardInfo extension methods SetSteelTrapPortrait(), SetBrokenShieldPortrait()
- Added public method TakeDamagePatches.BreakShield() for controlling DeathShield logic
- DeathShield logic now accounts for multiple stacks (DeathShield is not stackable by default)

Alt portraits for SteelTrap and lost shield, more triggers for TakeDamage

---

InscryptionAPI/Triggers/Interfaces.cs
InscryptionAPI/Triggers/TakeDamagePatches.cs

Generally with every other TriggerPriority the highest priority is called first, but this isn't the case with IModifyDamageTaken.
I think it's safe to say IModifyDamageTaken should also follow this trend, so all I've done is reversed the sort order.
I've also added XML Docs for IModifyDamageTaken and IPreTakeDamage.

Fixed issue with IModifyDamageTaken's Trigger Priority

---

InscryptionCommunityPatch/Card/BoxColliderNegativeScalingLogSpamFix.cs
InscryptionCommunityPatch/ResourceManagers/ActThreeBonesDisplayer.cs

This PR fixes two small defects that appear in Act 3:
1) There is a defect with the `BoxColliderNegativeScalingLogSpamFix` patch during Build-A-Card sequence. Because the TV screen displayer separates the displayed icon from the interactable, the interactable has no `MeshFilter` during this sequence. The fix is to ensure that the object actually has a MeshFilter before executing the patch.
2) The Act 3 Bones Displayer TV screen overlaps with the effect of P03's face change due to where the render camera lives in the TV layer. This means that the bones displayer shows a static effect every time P03's face changes during battle. The fix is to move the render camera to a different place in world space.

Misc bug fixes

---

InscryptionAPI/Card/CardManager.cs

When calling `CardManager.Remove`, cards will very rarely actually be removed. Reason being that, outside of the internal API, you will almost always be working with a copy of a `CardInfo`, and never the original `CardInfo` stored in `CardManager.NewCards` (which is a private list)
All this change does is that `CardManger.Remove` now loops through all cards in `NewCards` and removes any cards with matching names, instead of only removing exact matches

Fixed Cards not being Removed when using CardManager.Remove

---

CHANGELOG.md
InscryptionAPI/Card/TribeManager.cs
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionAPI/TalkingCards/CustomPaperTalkingCard.cs
InscryptionCommunityPatch/Card/Vanilla Ability Patches/SniperFix.cs
InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
docs/wiki/talking_cards.md

Made an oopsie when expanding sniper logic. Also fixed the auto-gen tribe choice texture being A) off-centre, and B) able to wrap the tribe icon texture around due to a lack of constraints

FIxed sniper targeting, auto-gen tribe choice texture

---

InscryptionAPI/Triggers/CustomTriggerFinder.cs
InscryptionCommunityPatch/Card/StackAbilityIcons.cs

This PR has two fixes in it:
**Non Card Trigger Receiver Fix**
This is a relatively simple fix. The list of non-card trigger receivers can theoretically change over time. If it changes during a trigger operation, you get an error: `InvalidOperationException: Collection was modified; enumeration operation may not execute.`
Most people aren't messing with this list, and perhaps people like me end up doing it somewhat incorrectly, but regardless there's no harm in caching the list of trigger receivers before we start iterating over them.
If a new non-card trigger receiver gets added during the iteration, now it simply won't trigger rather than throwing an error. If it gets deleted from the list, it will still fire (unless it was destroyed, in which case the `SafeIsUnityNull` check should …

Cache the list of trigger receivers before enumerating

---

InscryptionAPI/Card/TribeManager.cs

Currently the API will try to create additional renderers if the amount of 'tribeRenderers' is below the total amount on a card. This doesn't account for when the number of 'tribeRenderers' is 0, however, so this fixes that.
Note that this doesn't make tribe icons render outside Act 1, only stops the renderer from breaking.

Fix null error when trying to render tribe icons outside Act 1

---

CHANGELOG.md
InscryptionAPI/Card/ShieldManager.cs
InscryptionAPI/Encounters/ICustomExhaustSequence.cs
InscryptionAPI/Encounters/OpponentManager.cs
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/Rulebook/RuleBookRedirectManager.cs
InscryptionAPI/Slots/SlotModificationExtensions.cs
InscryptionAPI/Triggers/Interfaces.cs
InscryptionAPI/Triggers/TakeDamagePatches.cs

IShieldPreventedDamage is called after a shielded card is struck and loses a shield. ICustomExhaustSequence is for Opponents and allows the player to modify what happens when the player exhausts their draw piles.

Added IShieldPreventedDamage trigger and ICustomExhaustSequence

---

CHANGELOG.md
InscryptionAPI/Ascension/AscensionChallengePaginator.cs
InscryptionAPI/Ascension/ChallengeDisplayerPlus.cs
InscryptionAPI/Card/CardExtensionsCosts.cs
InscryptionAPI/Card/CostProperties.cs
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionCommunityPatch/InscryptionCommunityPatch.csproj
InscryptionCommunityPatch/InscryptionCommunityPatchPlugin.cs
InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
InscryptionCommunityPatch/Sequencers/BuyPeltsSmallTags.cs
README.md

Fixed positioning errors caused by having multiple custom boss challenge icons

Boss challenge icons fix

---

CHANGELOG.md
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionAPI/Pelts/PeltManager.cs
README.md
docs/wiki/getting_started.md

* Essentially fixes the pelt names as the trader would call them.

Fix Pelt Name when Trader says the line

---

CHANGELOG.md
InscryptionAPI/Card/CardExtensionsHelpers.cs
InscryptionAPI/Card/DamageShieldBehaviour.cs
InscryptionAPI/Card/ShieldManager.cs
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionCommunityPatch/Card/StackAbilityIcons.cs

Removes test code causing shields to persist perpetually.
Minor fixes for shield stack visuals.

Fix shields persisting, minor visual fixes
