Models/AbilityIdentifier.cs
Models/EvolveIdentifier.cs
Models/IceCubeIdentifier.cs
Models/TailIdentifier.cs

Works with both custom cards and edited cards created using jsonloader

Fix for Cyclical referencing identifiers

---

Models/NewCardAppearanceBehaviour.cs
Patches/Card_ApplyAppearanceBehaviours_NewCardAppearanceBehaviour.cs

**Create a background**
var newBackgroundBehaviour = NewCardAppearanceBehaviour.AddNewBackground(typeof(XelNagaBackground), "Xel'Naga");
CustomAppearance = newBackgroundBehaviour.Appearance;
**Assign a custom background to a card**
List<CardAppearanceBehaviour.Appearance> appearances = new List<CardAppearanceBehaviour.Appearance>{ XelNagaBackground.CustomAppearance };
new CustomCard("Squirrel") { appearanceBehaviour = appearances };

Support for custom card backgrounds

---

InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionAPI/Saves/ModdedSaveData.cs

This fixes two simple defects:
1) The GUID for the API is set to the correct value.
2) The Modded Save Manager now does a null check before converting saved values to strings.

Two defect fixes

---

InscryptionAPI/Ascension/AscensionChallengeScreen.cs
InscryptionAPI/Ascension/AscensionRunSetupScreenBase.cs
InscryptionAPI/Card/AbilityExtensions.cs
InscryptionAPI/Encounters/AIManager.cs
InscryptionAPI/Encounters/BossManager.cs
InscryptionAPI/Encounters/EncounterExtensions.cs
InscryptionAPI/Encounters/SpecialSequenceManager.cs
InscryptionAPI/Guid/CustomTypePatches.cs
README.md

(Sorry for the branch name)
This PR adds OpponentManager, SpecialSequenceManager, and AIManager, as well as documentation in the README on how to use all three of these.
It also has a couple of small defect fixes.

Boss, special sequencer, and AI managers

---

InscryptionAPI/Ascension/AscensionChallengePaginator.cs
InscryptionAPI/Ascension/AscensionChallengeScreen.cs
InscryptionAPI/Ascension/AscensionRunSetupScreenBase.cs
InscryptionAPI/Ascension/ChallengeManager.cs
InscryptionAPI/Ascension/StarterDeckManager.cs
InscryptionAPI/Ascension/StarterDeckPaginator.cs
InscryptionAPI/Ascension/StarterDeckSelectScreen.cs
InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Card/CardManager.cs
InscryptionAPI/Helpers/TextureHelper.cs
README.md

Adds the starter deck manager API and updates the starter deck screen to have scroll arrows to go between pages of starter decks.
Also updates the challenge manager and challenge screen patches to match the updated behavior of the starter deck API.

Starter decks

---

InscryptionAPI/Card/CardExtensions.cs

Based on feedback from the discord: SetRare no longer applies the appearance behavior "RareCardColors"

Rare card colors

---

InscryptionAPI/Ascension/AscensionChallengePaginator.cs
InscryptionAPI/Ascension/AscensionChallengeScreen.cs
InscryptionCommunityPatch/InscryptionCommunityPatchPlugin.cs
InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs

This PR fixes defects with the challenge screen pages

Fixed the challenge paginator post full-release

---

InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Compatibility/NewCard.cs

Note: I may have missed something that was fixed in the current branch as I just copy pasted over my file from the other large PR.
This also fixes the tail portrait setter to `_tailportrait` from "_pixelportrait"

Refactored and added documentation for CardExtensions.

---

InscryptionAPI/Card/CustomTriggers.cs
InscryptionAPI/Triggers/Attributes.cs
InscryptionAPI/Triggers/CustomGlobalTriggerHandler.cs
InscryptionAPI/Triggers/CustomTrigger.cs
InscryptionAPI/Triggers/CustomTriggerArgHolder.cs
InscryptionAPI/Triggers/CustomTriggerPatches.cs
InscryptionAPI/Triggers/TriggerIdentification.cs

Custom triggers

---

InscryptionCommunityPatch/Card/Act1LatchAbilityFix.cs

Also fixed prefix throwing exceptions as there was no annotation for the Prefix patch.

Refactored and cleaned up latch patch.

---

InscryptionCommunityPatch/Card/BoxColliderNegativeScalingLogSpamFix.cs

Added patch to fix warning log spam for flipped icons

---

InscryptionAPI/Card/TribeManager.cs

even though the tribeapi bug thingy should have been fixed already this adds even more safety precautions so it will never ever ever ever happen

Extra TribeAPI safety precautions

---

InscryptionAPI/Regions/RegionManager.cs

right now, region variant random is always the same for the same regions of the same save file. this pull request fixes that

Region random fix

---

InscryptionCommunityPatch/Card/AdditionalIcons.cs
InscryptionCommunityPatch/Card/Part3StatIcons.cs

This PR will allow special stat icons to render on cards in act 3

Make special stat icons render on disk cards (act 3)

---

InscryptionAPI/Triggers/CustomTriggerFinder.cs
InscryptionCommunityPatch/Card/Part3StatIcons.cs

A quick bugfix for Part 3 Stat Icons to properly null check some things.

Quick bugfix for part3 stat icons

---

CHANGELOG.md
InscryptionCommunityPatch/Card/Act1LatchAbilityFix.cs

As the title says, this PR fixes the Latch fix so that it actually works, and updates the changelog to include all previous updates plus this current update

Fixed latch fix, updated changelog

---

InscryptionAPI/Totems/TotemManager.cs

Only affected by mods that add their own custom totem head

Fixed mod added totem heads not showing after being chosen

---

InscryptionCommunityPatch/Card/SentryInteractionFixes.cs
InscryptionCommunityPatch/Card/SentryPackMuleFixes.cs
InscryptionCommunityPatch/Card/SentrySlotAttackSlotFix.cs
InscryptionCommunityPatch/Card/SentryTailOnHitFix.cs

Rewrote the broken part of the sentry fix so it no longer overwrites patches to SlotAttackSlot

New sentry fix

---

InscryptionAPI/Card/CardExtensions.cs
InscryptionCommunityPatch/Card/SelfAttackDamagePatch.cs
InscryptionCommunityPatch/Card/SentryInteractionFixes.cs
InscryptionCommunityPatch/Card/SentryPackMuleFixes.cs
InscryptionCommunityPatch/Card/SentryTailOnHitFix.cs
InscryptionCommunityPatch/Card/SlotAttackSlotFixes.cs

Adds 3 new helper extensions for abilities, traits, and special abilities:
HasAnyOf<> : returns true if PlayableCard/CardInfo has at least 1 of the given abilities/traits/specials
LacksAll<> : returns true if PC/CI has none of the given A/T/SAs
HasAll<> returns true if PC/CI has all of the given A/T/SAs
Also changed the protection level of some of the patch classes, and fixed a couple minor typos in the summaries for other extensions

More helper extensions

---

InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs

- Added tweening to energy drone when moving on and off-board
- Fixed visual bug where energy cells wouldn't start in their closed state in successive battles

Energy drone fixes/additions

---

InscryptionAPI/InscryptionAPIPlugin.cs

Changed the warning informing players they have outdated plugins installed to now list said outdated plugins in the console.

New warning for outdated plugins

---

InscryptionCommunityPatch/Card/SelfAttackDamagePatch.cs
InscryptionCommunityPatch/Sequencers/PackRatNodeBackgroundFix.cs

Fixed a visual bug where the Pack Rat card wouldn't have the Rare card background when obtained at the item node

Pack Rat visual fix

---

CHANGELOG.md
InscryptionAPI/InscryptionAPIPlugin.cs

Everytime I forget to add my changes to the changelog, an angel eats pavement and dies.
Added my fixes for 2.7.2 and 2.7.1.

Updated changelog

---

CHANGELOG.md
InscryptionCommunityPatch/Card/SniperFix.cs

Opponent AI in the sniper fix will no longer target Repulsive cards unless there's no other option.
Also cleaned up a couple unneeded lines/assignments

Sniper fix now accounts for Repulsive ability

---

InscryptionCommunityPatch/Card/Act1LatchAbilityFix.cs

More specifically, I rewrote the code to use a fixed version of the previous method the fix used for adding the latch mod (since it also works for act 2 cards), instead of whatever I was doing.

Fixed latch abilities not working in Act 2

---

CHANGELOG.md
InscryptionAPI/Card/AbilityManager.cs
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionCommunityPatch/Card/Act1LatchAbilityFix.cs

Fixed latch fix modifying the base info
Fixed ability stacks activating twice when they shouldn't

Hotfixes for 2.7.3

---

InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/Card/TribeManager.cs
InscryptionAPI/Totems/TotemManager.cs

Fixed tribal choice nodes being able to select custom tribes that don't have any obtainable cards.
Added some CardInfo extensions for checking CardMetaCategories, and standardised the descriptions of card extension methods.

Tribe-related fixes and extensions

---

InscryptionAPI/Ascension/AscensionChallengePaginator.cs
InscryptionAPI/InscryptionAPIPlugin.cs

- Adjusted how challenge arrow positions are determined
- Added config for forcing arrows to appear at the top

Challenge arrow tweaks

---

docs/README.md
docs/wiki/index.md

Rearranged sections, reworded some parts, expanded on some sections (primarily PeltManager), added info regarding upcoming features

Wiki tweaks and additions

---

InscryptionAPI/Card/CardManager.cs
InscryptionAPI/Dialogue/DialogueManager.cs
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionAPI/TalkingCards/Create/EmotionManager.cs

Also commented out debug warning in DialogueManager because it wasn't working as intended and I'm too lazy to make it do so.

Fixed dialogue with the "[end]" code breaking the game

---

InscryptionCommunityPatch/Card/SacrificeTokensFix.cs

Sacrifice tokens now stack on each other above 4 tokens
Moved sacrifice tokens in Act 3 to the side of the board

Sacrifice token visual adjustments

---

InscryptionAPI/Card/AbilityManager.cs
InscryptionAPI/Card/CardExtensions.cs
InscryptionCommunityPatch/Card/Act1LatchAbilityFix.cs
InscryptionCommunityPatch/Card/RandomAbilityPatches.cs

Amorphous now works for opponent cards and after evolving

Amorphous fixes

---

InscryptionAPI/Card/CardExtensions.cs

Added SetGemify extension for making cards that are Gemified by default
Added another SetGemsCost extension that uses params
Minor code tweak

SetGemify extension

---

docs/wiki/index.md

Updated API Wiki docs to have installation info on how to mod.

Updated API Wiki docs to have installation info on how to mod.

---

.github/workflows/main.yml
InscryptionAPI/Helpers/CustomFields.cs
InscryptionAPI/Triggers/CustomTriggerFinder.cs
InscryptionAPI/Triggers/CustomTriggerPatches.cs
InscryptionAPI/Triggers/Interfaces.cs
InscryptionAPI/Triggers/SlotAttackSlotPatches.cs
InscryptionAPI/Triggers/TakeDamagePatches.cs

Added a new trigger inspired by IModifyDamageTaken, but for direct damage
Relies on CustomFields from Pr #277

Added Some new Triggers

---

CHANGELOG.md
InscryptionAPI/Card/AbilityManager.cs
InscryptionAPI/Card/CardExtensions.cs
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs

Specifically, rewrote the patch to A) work again , and B) work with TriggersOncePerStack again again again

Re-re-fixed stacking abilities triggering twice as often as they should

---

InscryptionAPI/Card/CardManager.cs

Relevant bug report can be found here: #283

Fixed mods on copied cards being lost on card sync

---

CHANGELOG.md
InscryptionAPI/Card/AbilityExtensions.cs
InscryptionAPI/Card/AbilityManager.cs
InscryptionAPI/Card/CardExtensionsHelpers.cs
InscryptionAPI/Card/TribeManager.cs
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionAPI/Totems/TotemManager.cs
InscryptionAPI/Triggers/TakeDamagePatches.cs
InscryptionCommunityPatch/Card/Vanilla Ability Patches/Act2CuckooFix.cs
InscryptionCommunityPatch/Card/Vanilla Ability Patches/DrawCopyOnDeathFix.cs
InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
InscryptionCommunityPatch/Sequencers/PackRatNodeBackgroundFix.cs
InscryptionCommunityPatch/Sequencers/TradeableTalkingCardFix.cs

-Added GetStatIconHealthBuffs
-Added TransformIntoCardAboveHand
-Added some null checks
-Fixed DrawCopyOnDeath warnings

Added card extensions, null checks, fixed DrawCopyOnDeath warnings

---

InscryptionAPI/Card/AbilityExtensions.cs
InscryptionAPI/Card/AbilityManager.cs
InscryptionAPI/Card/CardExtensionsHelpers.cs
InscryptionAPI/Card/ShieldManager.cs
InscryptionCommunityPatch/Card/StackAbilityIcons.cs

Added ShieldManager.AllShieldAbilities, more extension methods, force-reset lostShield field when calling ResetShield, fix sigil stacking (again again again)

More shield fixes and stuff

---

CHANGELOG.md
InscryptionAPI/InscryptionAPI.csproj
InscryptionAPI/InscryptionAPIPlugin.cs
InscryptionCommunityPatch/InscryptionCommunityPatch.csproj
docs/wiki/rulebook.md

Fixed rulebook breaking when playing with no custom rulebook sections

Fixed RuleBookManager not syncing correctly
